---
title: "Le travail de Wenjun Zhao **[est disponible ici](https://github.com/claudia0524/PSBX/blob/main/gr03_Wenjun_ZHAO_R/gr03_Wenjun_ZHAO_ggplot2.pdf)**"
author: "Amine Benoucief"
date: "20/12/2020"
output:
  pdf_document: default
  html_document: default
---

*SYNTHESE DU TRAVAIL EN QUESTION*

ggplot2 est un package de data visualisation qui ameliore la qualite et l'esthetique des graphiques. C'est un bon travail qui resume bien les fonctionnalite du package. Wenjun a su bien expliquer ses lignes de codes. Cependant d'autres type de visuel aurait pu etre integrer au code pour mettre en valeur la richesse et la variete de ggplot2. De meme, pas de bibliographie nous ne savons pas si elle s'est inspiree d`un travail ou elle a cree elle meme ses examples (si oui il fallait le preciser).

# Overview

ggplot2 est un système de création graphique déclarative, basé sur The Grammar of Graphics. Vous fournissez les données, dites à ggplot2 comment mapper des variables à l'esthétique, quelles primitives graphiques utiliser et il s'occupe des détails.

# Installation

Le moyen le plus simple d'obtenir ggplot2 est d'installer tout le tidyverse:

*install.packages("tidyverse")*

Sinon, installez simplement ggplot2:

*install.packages("ggplot2")*

Ou la version de développement de GitHub:

*install.packages ("devtools")*

*devtools::install_github("tidyverse/ggplot2")*

# Utilisation

Il est difficile de décrire succinctement le fonctionnement de ggplot2 car il incarne une philosophie profonde de la visualisation. Cependant, dans la plupart des cas, vous commencez avec *ggplot ()*, fournissez un jeu de données et une cartographie esthétique (*avec aes ()*). Vous ajoutez ensuite des couches (*comme geom_point ()* ou *geom_histogram ()*), des échelles (*comme scale_colour_brewer ()*), des spécifications de facettes (*comme facet_wrap ()*) et des systèmes de coordonnées (*comme coord_flip ()*).


```{r}
library(ggplot2)
ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

**EVALUATION DU TRAVAIL EN QUESTION**

Critère 1 : Visuel sur pdf             3/4 Agreable a lire. 

Critère 2 : Originalite du code        3/4 Wenjun a bien montre comment utiliser la fonction.  

Critère 3 : Fonctionnalité du code     4/4 tout fonctionne.

Critère 4 : Lisibilité du code         3/4 très simple et lisible.

Critère 5 : Explications données       3/4 Explications claire sur le code et comment fonctionne ggplot.
**CONCULSION**

Globalement bon travail qui exlique rapidement ggplot2. Un peu plus de visuel aurait ete appreciable. 